services:
  ergo:
    image: ergochat/ergo:latest
    container_name: ircord-ergo
    ports:
      - "6667:6667"   # Plain IRC
      - "6697:6697"   # SSL IRC
      - "8067:8067"   # WebSocket
    volumes:
      - ./.ergo/ergo:/ircd
      - ./.ergo/ircd.yaml:/ircd/ircd.yaml
    restart: unless-stopped
